name: Android CI

on:
  push:
    branches: [ main, develop, "feature/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew || true

      - name: Build Debug (if project present)
        run: ./gradlew assembleDebug --stacktrace || echo "Project not initialized yet"

      - name: Unit tests
        run: ./gradlew testDebugUnitTest --stacktrace || echo "No tests yet"

      - name: Lint
        run: ./gradlew lint || echo "No lint yet"
